server:
  port: 9090
  ### Swagger-ui
doc:
  show-actuator: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    csrf:
      enabled: true
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:9090
    title: Gentle Monster API
    version: 1.0.0
    enabled: true
    swagger-ui:
      enabled: true
spring:
  application:
    name: gentlemonster
  config:
    import: classpath:env.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
  messages:
    basename: messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      cookie:
      name: JSESSIONID
      http-only: true
      secure: false
      timeout: 30m
      persistent: true
      tracking-modes: cookie
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      enabled: true
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  # Rate limiting configuration
  ratelimit:
    public:
      requests: 3
      duration: PT1M
    admin:
      requests: 1000
      duration: PT1M

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
jwt:
  expiration: ${JWT_EXPIRATION} # 30 ngày = 30 * 24h * 60p * 60s
  jwtRefreshExpiration: ${JWT_REFRESH_EXPIRATION} #60 days = 60 * 24 * 60 * 60
  secretKey: ${JWT_SECRET_KEY}
